name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Any steps to take and/or commands to run to reproduce this issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Mattermost and plugin version
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context / Screenshots / Logs
      description: If applicable, add screenshots, logs or any additional context to help explain your problem.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report! :smile:
