name: 'ci'
on:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  contents: 'read'

jobs:
  plugin-ci:
    uses: 'mattermost/actions-workflows/.github/workflows/community-plugin-ci.yml@main'
    secrets: 'inherit'
